# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c1e04f75cc9185ea6f2da965691fa534883eab01bd5ec3eb610d4acd9a6290fb107700423f901a02d764bc45e7e37c125ecab06d0974ac49fdc8aae1dd5ace9

test:
  secret_key_base: e1f4000c8c69a04e32b8be4e87f4b7f47a4c430005197a33f89e94dc7184fe215e188a11b6cc64d38e01944bed28d7f0c8bd4b4c009b6f549059680474476407

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
